### ISSUE TITLE
Feature Request: Add margin/padding options?

### ISSUE THREAD

**Issue by jpecor** [ladyada/Adafruit_CircuitPython_Display_Button#1]
I've been playing around with adding the ability to define custom margin/padding to adafruit_button.py.  

The margin allows me to create visual space between buttons packed on a grid without worrying about the math before creating each button.  

The padding is applied inside of the button shape itself and is used to constrain the bounding box for contain() function.  My thought is that this helps a bit to prevent reading a touch in the wrong button area.

I currently have them both defined as (x,y) tuples so I can adjust each axis independently.  Though, I can't contrive a good example of when I'd do that.  And, I know that there has been a move away from passing tuples in favor of independent x/y arguments. 

While this works well for my project, I haven't convinced myself yet that it's a great idea, overall.   I thought I'd capture it here, anyway, and see what kind of feedback I get.

Here's an example of my PyPortal with no margin and then again with margin=(1,1).

![IMG_8034](https://user-images.githubusercontent.com/14111408/55129058-b7070680-50e3-11e9-930f-5da6f3dfa7c5.jpg)
![IMG_8032](https://user-images.githubusercontent.com/14111408/55129062-bbcbba80-50e3-11e9-9e4d-2d09eacfe130.jpg)

**Comment by ladyada** [comment]
i totally know where you're coming from - its annoying to do the padding subtraction, but i want to keep Button dimensions as-is... this would mean having to update your code to do the math but, how its traditionally done....i like a 10-pixel buffer :) 
see 
https://github.com/ladyada/Adafruit_CircuitPython_Display_Button/blob/master/examples/display_button_soundboard.py
for a way to define a lot of buttons easily

**Comment by jpecor** [comment]
Understood.   Thanks for the pointer to @kattni 's project.  I was just looking at the pixel color picker project this morning that uses a similar approach.   I'll plan to use the Button class as-is, though I may create a derived class for this specific project.  It will make for good practice with CircuitPython OOP.   Thanks @ladyada!

**Comment by ladyada** [comment]
awesome, can't wait to see what you make :D
