### ISSUE TITLE
Documentation badge link 404 not found

### ISSUE THREAD

**Issue by NanoDano** [ladyada/Adafruit_CircuitPython_Display_Button#2]
The badge on the README links to https://circuitpython.readthedocs.io/projects/display_shapes/en/latest/ but when visiting it there is a 404 error. It might just be a configuration issue with this repository needed a proper webhook configured between ReadTheDocs and GitHub, or maybe the link just needs to point somewhere else.

**Comment by ladyada** [comment]
this should be on 
https://github.com/adafruit/Adafruit_CircuitPython_Display_Shapes
not my fork, but that link isnt working either?

**Comment by siddacious** [comment]
@ladyada I fixed this in the adafruit repo; this can be closed

**Comment by siddacious** [comment]
same typo was in both the shape and button libs, fixed both
