### ISSUE TITLE
Assigning black fill + outline prevents body style formatting

### ISSUE THREAD

**Issue by jpecor** [ladyada/Adafruit_CircuitPython_Display_Button#3]
The ```if outline_color or fill color:``` conditional fails if both fill_color and outline_color are set to 0x000000.  As a result, the body style formatting is never applied, and the button is not added to the display group.

**Comment by ladyada** [comment]
hiya please open issues here
https://github.com/adafruit/Adafruit_CircuitPython_Display_Button
